# Generated by Django 4.2.7 on 2023-11-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('baseentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_sale.baseentity')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category/%Y/%m/%d')),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='app_sale.category')),
            ],
            bases=('app_sale.baseentity',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('baseentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_sale.baseentity')),
                ('full_name', models.CharField(blank=True, max_length=70, null=True)),
                ('phn_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
            ],
            bases=('app_sale.baseentity',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('baseentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_sale.baseentity')),
                ('name', models.CharField(max_length=80)),
            ],
            bases=('app_sale.baseentity',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('baseentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_sale.baseentity')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('product_image', models.ImageField(upload_to='product')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='app_sale.category')),
            ],
            bases=('app_sale.baseentity',),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('baseentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_sale.baseentity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('orderItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_sale.order')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='app_sale.product')),
            ],
            bases=('app_sale.baseentity',),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('baseentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_sale.baseentity')),
                ('name', models.CharField(max_length=120)),
                ('short_description', models.CharField(max_length=250)),
                ('full_description', models.TextField()),
                ('current_stock', models.IntegerField(default=0)),
                ('purchase_price', models.IntegerField(default=0)),
                ('sales_price', models.IntegerField(default=0)),
                ('promotional_price', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='inventory/%Y/%m/%d/')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productCategory', to='app_sale.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='inventory_tag', to='app_sale.tag')),
            ],
            bases=('app_sale.baseentity',),
        ),
    ]
