# Generated by Django 4.2.7 on 2023-12-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sale', '0002_alter_inventory_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='inventory/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
