# Generated by Django 4.2.7 on 2023-12-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sale', '0003_alter_inventory_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='inventory', verbose_name='Фото'),
        ),
    ]
