# Generated by Django 4.2.7 on 2023-12-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sale', '0004_alter_inventory_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='order',
            name='phn_number',
            field=models.CharField(max_length=20),
        ),
    ]
